### ISSUE TITLE
Plugin does not exist: rocketeer

### ISSUE THREAD

**Issue by xar** [Enrise/PHPCI-Rocketeer#1]
I have installed rocketeer plugin i see it at phpci plugins page. But when i try to run it by adding it to phpci.yml i get:
RUNNING PLUGIN: rocketeer
Plugin does not exist: rocketeer
Exception: Plugin failed: rocketeer

**Comment by eXistenZNL** [comment]
xar,

thanks for contacting us.

Did you run composer install? Adding a plugin via the PHPCI interface will only add it to the composer.json, but you still need to run composer install manually.

**Comment by rick-nu** [comment]
For more information on that, see: https://www.phptesting.org/wiki/custom-plugins-setup

**Comment by eXistenZNL** [comment]
xar,

also please let us know if this solved your problems, so we can close this issue.

greetings,

eX

**Comment by rick-nu** [comment]
Closing
